export default {
	map_service_location_oem: 'map_service_location_oem',
	map_user_oem: 'map_user_oem',
	map_user_repair_stage: 'map_user_repair_stage',
	mst_action_status: 'mst_action_status',
	mst_model: 'mst_model',
	mst_oem: 'mst_oem',
	mst_platform: 'mst_platform',
	mst_product: 'mst_product',
	mst_repair_stage: 'mst_repair_stage',
	mst_role: 'mst_role',
	mst_service_location: 'mst_service_location',
	mst_user: 'mst_user',
	mst_problem: 'mst_problem',
	mst_warrenty_status: 'mst_warrenty_status',
	tr_customer: 'tr_customer',
	tr_customer_address: 'tr_customer_address',
	tr_customer_product: 'tr_customer_product',
	tr_job_detail: 'tr_job_detail',
	tr_job_head: 'tr_job_head',
	tr_job_stage: 'tr_job_stage',
	vw_user: 'vw_user',
	vw_job_list: 'vw_job_list',
	map_job_problem: 'map_job_problem'
}
